modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="ores"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="assets/ores/icon_256.png"

[[dependencies.ores]]
modId="emi"
mandatory=false
versionRange="[1.1.0,)"
ordering="AFTER"
side="CLIENT"
